// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { CdpHelper, useSitecore } from '@sitecore-content-sdk/nextjs';
import { useEffect } from 'react';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
